name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      image: <<.Image>>
      dockerfile: Dockerfile
  release:
    needs:
      - build
    uses: clambin/workflows/.github/workflows/release.yaml@main

